# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'password_prototype' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for password_prototype
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  
  target 'password_prototypeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'password_prototypeUITests' do
    # Pods for testing
  end

end
