const utils = require('./utils');

exports.getGameWords = function (numPlayers, wordBankSize) {
    const numTotalWords = numPlayers * wordBankSize + 1;
    if (numTotalWords > wordList.length) {
        throw new Error("not enough words in word list to support game of this size.");
    }

    let allWords = utils.shuffleArray(wordList);
    let gameWords = allWords.slice(0, numTotalWords);
    return {
        startWord: gameWords[0],
        playerWordLists: utils.chunkArray(gameWords.slice(1), wordBankSize),
        availableWords: allWords.slice(numTotalWords)
    };

}

// Alphabetized list of ~100 curated words.
const wordList = [
    'advance',
    'age',
    'appliance',
    'audio',
    'autumn',
    'badge',
    'baker',
    'bar',
    'bird',
    'black',
    'blanket',
    'block',
    'blood',
    'book',
    'brain',
    'building',
    'camera',
    'captain',
    'card',
    'cart',
    'chain',
    'city',
    'coast',
    'college',
    'color',
    'construction',
    'court',
    'culture',
    'customer',
    'dance',
    'department',
    'dome',
    'drive',
    'editor',
    'energy',
    'fame',
    'field',
    'film',
    'floor',
    'frame',
    'gallery',
    'game',
    'home',
    'hotel',
    'house',
    'industry',
    'island',
    'jacket',
    'kingdom',
    'laser',
    'lens',
    'library',
    'life',
    'light',
    'line',
    'link',
    'machine',
    'magic',
    'money',
    'motor',
    'motorcycle',
    'movie',
    'music',
    'nuclear',
    'object',
    'office',
    'opera',
    'paper',
    'park',
    'party',
    'permit',
    'picture',
    'plant',
    'power',
    'prize',
    'property',
    'radio',
    'radius',
    'rock',
    'rocket',
    'score',
    'shadow',
    'shipment',
    'shoes',
    'sing',
    'sip',
    'sound',
    'speed',
    'stage',
    'stone',
    'student',
    'theater',
    'time',
    'triangle',
    'video',
    'water',
    'weather',
    'work',
    'world',
];